"""empty message

Revision ID: efb65b122693
Revises: 1b5fad9a6283
Create Date: 2025-05-04 15:54:02.948150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb65b122693'
down_revision = '1b5fad9a6283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav_profile_id_fk', sa.Integer(), nullable=False))
        batch_op.drop_constraint('unique_favourite', type_='unique')
        batch_op.create_unique_constraint('unique_favourite', ['user_id_fk', 'fav_profile_id_fk'])
        batch_op.drop_constraint('favourites_fav_user_id_fk_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'profiles', ['fav_profile_id_fk'], ['id'])
        batch_op.drop_column('fav_user_id_fk')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav_user_id_fk', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favourites_fav_user_id_fk_fkey', 'users', ['fav_user_id_fk'], ['id'])
        batch_op.drop_constraint('unique_favourite', type_='unique')
        batch_op.create_unique_constraint('unique_favourite', ['user_id_fk', 'fav_user_id_fk'])
        batch_op.drop_column('fav_profile_id_fk')

    # ### end Alembic commands ###
